#!/bin/sh
set -eu
export PYTHONPATH="${TALEBOOK_CALIBRE_RUNTIME:-/usr/lib/calibre}"
export LD_LIBRARY_PATH="${TALEBOOK_CALIBRE_LIB:-/usr/lib/talebook-calibre/lib}${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export PATH="${TALEBOOK_CALIBRE_BIN:-/usr/lib/talebook-calibre/bin}:$PATH"
export CALIBRE_STANDALONE_CONVERTER=1
export CALIBRE_STANDALONE_FORBID_QT=1
exec /usr/bin/python3 /usr/lib/calibre/run_ebook_convert_pdf.py "$@"
